import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { MapsAPI } from "./components/MapsAPI";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <MapsAPI>
        <body className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased`}>
          <main className="min-h-screen">{children}</main>
          <footer className="p-2 text-center">
            Feito com &#x2763; por{" "}
            <a className="underline underline-offset-2" target="_blank" href="https://github.com/ruanosena">
              ruanosena
            </a>
          </footer>
        </body>
      </MapsAPI>
    </html>
  );
}
